# Generated by Django 6.0.3 on 2026-04-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_available_today',
            field=models.BooleanField(default=True),
        ),
    ]
